export const datasProjects = [
  {
    title: 'Booki',
    description: 'Trouvez votre hébergement pour des vacances de rêves',
    image: 'images/mockups/P2_Booki.jpg',
    linkDemo: 'https://fabien-t.github.io/Fabien_P2/',
    linkGit: 'https://github.com/FABIEN-T/Fabien_P2',
    linkDemoColor: 'bg-[#0065FC]',
    tags: ['HTML', 'CSS', 'Responsive'],
    offsetY: 0,
  },
  {
    title: 'Ohmyfood',
    description: 'Entreprise de commande de repas en ligne',
    image: 'images/mockups/P3_Ohmyfood.jpg',
    linkDemo: 'https://fabien-t.github.io/FabienVarlet_3_03122021/public/',
    linkGit: 'https://github.com/FABIEN-T/FabienVarlet_3_03122021',
    linkDemoColor: 'bg-gradient-to-br from-[#FF79DA] to-[#9356DC]',
    tags: ['HTML', 'Sass', 'Animations CSS', 'Loader'],
    offsetY: 20,
  },
  {
    title: 'GameOn',
    description:
      'Entreprise spécialisée dans les conférences et les concours de jeux',
    image: 'images/mockups/P4_Gameon.jpg',
    linkDemo: 'https://fabien-t.github.io/GameOn-website-FR/starterOnly/',
    linkGit: 'https://github.com/FABIEN-T/GameOn-website-FR',
    linkDemoColor: 'bg-[#fe142f]',
    tags: ['HTML', 'CSS', 'Javascript', 'Modale', 'Formulaire'],
    offsetY: 40,
  },
  {
    title: 'Fisheye',
    description: 'Site de photographes freelance',
    image: 'images/mockups/P6_Fisheye.jpg',
    linkDemo: 'https://fabien-t.github.io/Front-End-Fisheye/public/index.html',
    linkGit: 'https://github.com/FABIEN-T/Front-End-Fisheye',
    linkDemoColor: 'bg-[#fe142f]',
    tags: [
      'HTML',
      'CSS',
      'Javascript',
      'Sass',
      'Accessibilité',
      'Site dyanmique',
    ],
    offsetY: 0,
  },
  {
    title: 'Les petits plats',
    description:
      'algorithme de recherche en JavaScript pour un site recettes de cuisine',
    image: 'images/mockups/P7_Les-petits-plats.jpg',
    linkDemo: 'https://fabien-t.github.io/Front-End-Fisheye/public/index.html',
    linkGit: 'https://github.com/FABIEN-T/Front-End-Fisheye',
    linkDemoColor: 'bg-[#D04F4F]',
    tags: ['HTML', 'Sass', 'Javascript', 'Tags', 'Json'],
    offsetY: 20,
  },
  {
    title: 'Billed',
    description: 'Débogage et tests',
    image: 'images/mockups/P9_Billed.jpg',
    linkDemo: '',
    linkGit: 'https://github.com/FABIEN-T/Kasa_FV',
    linkDemoColor: 'bg-[#ff6060]',
    tags: ['HTML', 'Sass', 'REACT', 'Json'],
    offsetY: 40,
  },
  {
    title: 'Kasa',
    description: 'Site de location d’appartements entre particuliers',
    image: 'images/mockups/P11_Kasa.jpg',
    linkDemo: 'https://kasa-fv.vercel.app/',
    linkGit: 'https://github.com/FABIEN-T/Kasa_FV',
    linkDemoColor: 'bg-[#ff6060]',
    tags: ['HTML', 'Sass', 'REACT', 'Json'],
    offsetY: 0,
  },
  {
    title: 'SportSee',
    description:
      'Tableau de bord analytique permettant à l’utilisateur de suivre ses progrès quotidiens (poids, nombre de calories brûlées, etc.)',
    image: 'images/mockups/P12_SportSee.jpg',
    linkDemo: '',
    linkGit: 'https://github.com/FABIEN-T/P12_SportSee',
    linkDemoColor: 'bg-[#ff0101]',
    tags: ['HTML', 'Sass', 'REACT', 'Recharts', 'Json'],
    offsetY: 20,
  },
  {
    title: 'Argent Bank',
    description: 'Site de location d’appartements entre particuliers',
    image: 'images/mockups/P13_Argent-Bank.jpg',
    linkDemo: '',
    linkGit: 'https://github.com/FABIEN-T/P13_Argent-Bank_Front',
    linkDemoColor: 'bg-[#ff6060]',
    tags: ['HTML', 'Sass', 'REACT', 'Json'],
    offsetY: 40,
  },
  {
    title: 'HR-net',
    description: 'Sass Jquery => REACT',
    image: 'images/mockups/P14_HRnet.jpg',
    linkDemo: 'https://p14-h-rnet-ruddy.vercel.app/',
    linkGit: 'https://github.com/FABIEN-T/P14_HRnet',
    linkDemoColor: 'bg-[#ff6060]',
    tags: ['HTML', 'Sass', 'REACT', 'Json'],
    offsetY: 0,
  },
  {
    title: 'Poterie des Tappes',
    description: 'Catalogue des artistes Christine Humann et Nelly Martinelli',
    image: 'images/mockups/Poterie.jpg',
    linkDemo: '',
    linkGit: '',
    linkDemoColor: 'bg-[#ff6060]',
    tags: ['HTML', 'Sass', 'REACT', 'Json'],
    offsetY: 40,
  },
  {
    title: 'Stud',
    description: 'Sass Jquery => REACT',
    image: 'images/mockups/Stud.jpg',
    linkDemo: '',
    linkGit: '',
    linkDemoColor: 'bg-[#ff6060]',
    tags: ['HTML', 'Sass', 'REACT', 'Json'],
    offsetY: 0,
  },
]
