export const datasProjects = [
  {
    title: 'Booki',
    description: 'Entreprise proposant un outil de planification de vacances',
    image: 'images/mockups/P2_Booki.jpg',
    linkDemo: 'https://fabien-t.github.io/Fabien_P2/',
    linkGit: 'https://github.com/FABIEN-T/Fabien_P2',
    linkDemoColor: 'bg-[#0065FC]',
    tagsBlue: ['HTML', 'CSS'],
    tagsRed: ['Responsive', 'Dev - Tools', 'Intégration de la maquette'],
    offsetY: 0,
  },
  {
    title: 'Ohmyfood',
    description: 'Entreprise de commande de repas en ligne',
    image: 'images/mockups/P3_Ohmyfood.jpg',
    linkDemo: 'https://fabien-t.github.io/FabienVarlet_3_03122021/public/',
    linkGit: 'https://github.com/FABIEN-T/FabienVarlet_3_03122021',
    linkDemoColor: 'bg-gradient-to-br from-[#FF79DA] to-[#9356DC]',
    tagsBlue: ['HTML', 'Sass'],
    tagsRed: [
      'Animations CSS',
      'Loader',
      'Intégration des maquettes',
      'Mobile first',
    ],
    offsetY: 20,
  },
  {
    title: 'GameOn',
    description:
      'Entreprise spécialisée dans les conférences et les concours de jeux',
    image: 'images/mockups/P4_Gameon.jpg',
    linkDemo: 'https://fabien-t.github.io/GameOn-website-FR/starterOnly/',
    linkGit: 'https://github.com/FABIEN-T/GameOn-website-FR',
    linkDemoColor: 'bg-[#fe142f]',
    tagsBlue: ['HTML', 'CSS', 'Javascript'],
    tagsRed: ['Modale', 'Formulaire', 'Validation des champs'],
    offsetY: 40,
  },
  {
    title: 'Fisheye',
    description: 'Site de photographes freelance',
    image: 'images/mockups/P6_Fisheye.jpg',
    linkDemo: 'https://fabien-t.github.io/Front-End-Fisheye/public/index.html',
    linkGit: 'https://github.com/FABIEN-T/Front-End-Fisheye',
    linkDemoColor: 'bg-[#fe142f]',
    tagsBlue: ['HTML', 'Javascript', 'Sass'],
    tagsRed: [
      'Maquette Figma',
      'Accessibilité',
      'Navigation du site avec le clavier',
      'Site dyanmique',
      'Json',
      'Factory Pattern',
      'Eslint',
    ],
    offsetY: 0,
  },
  {
    title: 'Les petits plats',
    description:
      'Algorithme de recherche en JavaScript pour un site recettes de cuisine',
    image: 'images/mockups/P7_Les-petits-plats.jpg',
    linkDemo: 'https://fabien-t.github.io/Les-petits-plats/public/',
    linkGit: 'https://github.com/FABIEN-T/Front-End-Fisheye',
    linkDemoColor: 'bg-[#D04F4F]',
    tagsBlue: ['HTML', 'Sass', 'Javascript'],
    tagsRed: [
      'Json',
      'Intégration maquette Figma',
      'Optimisation du moteur de recherche',
      'Recherche avancée par mots clés',
      'Test de deux implémentations différentes',
      'Fiche d’investigation et de  fonctionnalité',
    ],
    offsetY: 20,
  },
  {
    title: 'Billed',
    description: 'Débogage et tests',
    image: 'images/mockups/P9_Billed.jpg',
    linkDemo: '',
    linkGit: 'https://github.com/FABIEN-T/Kasa_FV',
    linkDemoColor: 'bg-[#ff6060]',
    tagsBlue: ['Jest'],
    tagsRed: [
      'Chrome debugger',
      'Tests unitaires et d’intégration',
      'Plan de test End-to-End',
    ],
    offsetY: 40,
  },
  {
    title: 'Learn@Home',
    description: 'Définition des besoins pour une app de soutien scolaire',
    details: [
      '• Synthèse des attentes',
      '• Maquettes haute fidélité',
      '• Diagrammes de cas d’usages',
      ' • User Stories ou récits utilisateurs',
      '• Tableau Kanban (découpage du projet en blocs de fonctionnalités)',
    ],
    image: 'images/mockups/P10_LearnHome.jpg',
    linkDemo:
      'https://www.figma.com/file/Awk1gYG7RVguSbjv7wejqQ/P10_Fabien-VARLET_Maquettes-Learn%40Home?type=design&node-id=1-3&mode=design',
    linkGit: '',
    linkDemoColor: 'bg-[#ff6060]',
    tagsBlue: [],
    tagsRed: [
      'Synthèse des attentes',
      'Création des maquettes',
      'Diagrammes de cas d’usages',
      'User Stories',
      'Tableau Kanban',
    ],
    offsetY: 40,
  },
  {
    title: 'Kasa',
    description: 'Site de location d’appartements entre particuliers',
    image: 'images/mockups/P11_Kasa.jpg',
    linkDemo: 'https://kasa-fv.vercel.app/',
    linkGit: 'https://github.com/FABIEN-T/Kasa_FV',
    linkDemoColor: 'bg-[#ff6060]',
    tagsBlue: ['HTML', 'Sass', 'REACT', 'React Router'],
    tagsRed: [
      'Responsive',
      'Code legacy',
      'Refonte totale en React',
      'Json',
      'CRA',
    ],
    offsetY: 0,
  },
  {
    title: 'SportSee',
    description:
      'Tableau de bord analytique permettant à l’utilisateur de suivre ses progrès quotidiens (poids, nombre de calories brûlées, etc.)',
    image: 'images/mockups/P12_SportSee.jpg',
    linkDemo: '',
    linkGit: 'https://github.com/FABIEN-T/P12_SportSee',
    linkDemoColor: 'bg-[#ff0101]',
    tagsBlue: ['HTML', 'Sass', 'REACT', 'React Router', 'Recharts'],
    tagsRed: [
      'Json',
      'CRA',
      'Récupéreration données depuis API sous Node.js',
      'Documentation technique avec JsDoc',
    ],
    offsetY: 20,
  },
  {
    title: 'Argent Bank',
    description:
      'Application web bancaire avec un nouveau système d’authentification permettant à l’utilisateur de se connecter et de gérer son compte et son profil',
    image: 'images/mockups/P13_Argent-Bank.jpg',
    linkDemo: '',
    linkGit: 'https://github.com/FABIEN-T/P13_Argent-Bank_Front',
    linkDemoColor: 'bg-[#ff6060]',
    tagsBlue: [
      'HTML',
      'CSS',
      'REACT',
      'Redux',
      'Redux Toolkit',
      'React-hook-form',
      'Axios',
    ],
    tagsRed: [
      'Système d’authentification',
      'Backend Node.js',
      'MongoDb',
      'Fichier swagger',
      'Responsive',
      'CRA',
      'Json',
    ],
    offsetY: 40,
  },
  {
    title: 'HR-net',
    description:
      'Application de gestion des employés utilisant Jquery convertie en REACT',
    image: 'images/mockups/P14_HRnet.jpg',
    linkDemo: 'https://p14-h-rnet-ruddy.vercel.app/',
    linkGit: 'https://github.com/FABIEN-T/P14_HRnet',
    linkDemoColor: 'bg-[#ff6060]',
    tagsBlue: ['HTML', 'Styled-Components', 'REACT'],
    tagsRed: [
      'Dette Technologique',
      'Conversion des plug-in jQuery en React',
      'Publication d’un Package Npm : modale',
      'Gestionnaire d’état avec useContext et useReducer',
      'Atomic-Design',
      'Responsive',
      'Json',
      'Initialisation projet avec Vite',
    ],
    offsetY: 0,
  },
  {
    title: 'Poterie des Tappes',
    description: 'Catalogue des artistes Christine Humann et Nelly Martinelli',
    image: 'images/mockups/Poterie.jpg',
    linkDemo: '',
    linkGit: '',
    linkDemoColor: 'bg-[#ff6060]',
    tagsBlue: ['HTML', 'Sass', 'REACT', 'Json'],
    tagsRed: ['Responsive'],
    offsetY: 40,
  },
  {
    title: 'Stud & Yo',
    description:
      'Site de présentation du groupe pour démarcher les programmateurs',
    image: 'images/mockups/Stud.jpg',
    linkDemo: '',
    linkGit: '',
    linkDemoColor: 'bg-[#ff6060]',
    tagsBlue: ['HTML', 'Sass', 'REACT', 'Json'],
    tagsRed: ['Responsive'],
    offsetY: 0,
  },
]
